spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee-db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
    database: mysql
  application:
    name: EMPLOYEE-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
